[tools]
aws-cli = "latest"
aws-sam-cli = "latest"
bat = "latest"
claude = "latest"
driftctl = "latest"
eza = "latest"
fd = "latest"
# gcloud = "latest"
gemini-cli = "latest"
# gitconfig = "latest"
# github-markdown-toc = "latest"
# gitleaks = "latest"
glow = "latest" # terminal markdown render
hcl2json = "latest"
infracost = "latest"
lazydocker = "latest"
lazygit = "latest"
localstack = "latest"
# liquibase = "latest"
# markdownlint-cli2 = "latest"
# mkcert = "latest"
node = { version = "latest", postinstall = "corepack enable" }
opentofu = "latest"
# pre-commit = "latest"
# prettier = "latest"
# python = "latest"
ripgrep = "latest"
# semver = "latest"
# semtag = "latest"
# shellcheck = "latest"
# terradozer = "latest"
# terraform = "latest"
# terrascan = "latest"
# tfsec = "latest"
# tflint = "latest"
# terraform-docs = "latest"
# terragrunt = "latest"
# tfupdate = "latest"
# terraformer = "latest"
# terraform-ls = "latest"
# terraform-lsp = "latest"
# terramate = "latest" # https://terramate.io/
# terrascan = "latest"
# tf-summarize = "latest"
# tf-notify = "latest"
# tfstate-lookup = "latest"
yamlfmt = "latest"
yamllint = "latest"
zoxide = "latest"
