[tools]
aws-cli = "2.32.3"
aws-sam-cli = "1.150.1"
bat = "latest"
claude = "latest"
driftctl = "latest"
eza = "latest"
fd = "latest"
glow = "latest"
hcl2json = "latest"
infracost = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
node = "24.10.0"
"npm:@mirohq/cloud-data-import" = "latest"
"npm:@shopify/cli" = "latest"
opentofu = "1.10.7"
python = "3.12.11"
ripgrep = "latest"
terraform = "1.14.0"
terragrunt = "0.93.12"
tlrc = "latest"
yamlfmt = "latest"
yamllint = "latest"
yarn = "latest"
yq = "latest"