#SPDX-License-Identifier: MIT-0
---
# tasks file for cli tools

  - name: Install Cursor
    ansible.builtin.shell:
      cmd: curl https://cursor.com/install -fsS | bash
    when: ansible_os_family == "Darwin"
    become: false
    register: cursor_install_result

  - name: Install Gemini CLI
    community.general.homebrew:
      name: gemini-cli
      state: present
    when: ansible_os_family == "Darwin"
    become: false

  - name: Install WezTerm
    community.general.homebrew_cask:
      name: wezterm
      state: present
    when: ansible_os_family == "Darwin"
    become: false

  - name: Install RectanglePro
    community.general.homebrew_cask:
      name: rectangle-pro
      state: present
      install_options: force
    when: ansible_os_family == "Darwin"
    become: false

  - name: Install BetterDisplay
    community.general.homebrew_cask:
      name: betterdisplay
      state: present
    when: ansible_os_family == "Darwin"
    become: false
  
  - name: Install Neovim
    community.general.homebrew:
      name: neovim
      state: present
    when: ansible_os_family == "Darwin"
    become: false