#SPDX-License-Identifier: MIT-0
---
# tasks file for browsers

- name: Install Brave Browser
  community.general.homebrew_cask:
    name: brave-browser
    state: present
  when: ansible_os_family == "Darwin"
  become: false

