---
- name: Create .local/bin directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Check if Amazon Q app exists
  ansible.builtin.stat:
    path: "/Applications/Amazon Q.app/Contents/MacOS/q"
  register: amazon_q_binary_check

- name: Create symlink for q command in user bin directory
  ansible.builtin.file:
    src: "/Applications/Amazon Q.app/Contents/MacOS/q"
    dest: "{{ ansible_env.HOME }}/.local/bin/q"
    state: link
    mode: '0755'
  when: amazon_q_binary_check.stat.exists

- name: Check if q CLI is available
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/q --version"
  register: q_cli_check
  failed_when: false
  changed_when: false
  when: amazon_q_binary_check.stat.exists

- name: Enable Amazon Q Wezterm integration
  ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/q integrations install input-method"
  when: 
    - amazon_q_binary_check.stat.exists
    - q_cli_check.rc == 0
    - amazon_q_install_input_method | bool
  register: q_wezterm_integration
  changed_when: "'already installed' not in q_wezterm_integration.stdout"
  failed_when: false

- name: Install AWS CDK
  community.general.npm:
    name: "aws-cdk"
    global: true
    state: present

