---
- name: Install TypeScript (Global)
  community.general.npm:
    name: "typescript"
    global: true
    state: present

- name: Install Mise-en-place
  community.general.homebrew:
    name: "mise"
    state: latest