---
- name: Import packages tasks
  import_tasks: packages.yml

- name: Import shell configuration tasks
  import_tasks: shell.yml

- name: Import AWS tasks
  import_tasks: aws.yml

- name: Import CLI tasks
  import_tasks: cli.yml

- name: Import Logitech tasks
  import_tasks: logitech.yml

- name: Import font configuration tasks
  import_tasks: fonts_config.yml

- name: Configure macOS defaults
  import_tasks: defaults.yml

- name: Import development tasks
  import_tasks: development.yml