#SPDX-License-Identifier: MIT-0
---
# tasks file for gcloud_uninstall

- name: Uninstall Google Cloud CLI via Homebrew on macOS
  community.general.homebrew_cask:
    name: google-cloud-sdk
    state: absent
  when: ansible_os_family == "Darwin"
  become: false

- name: Uninstall Google Cloud CLI via APT on Debian-based systems
  ansible.builtin.apt:
    name: google-cloud-cli
    state: absent
    autoremove: true
  when: ansible_os_family == "Debian"
  become: true

- name: Uninstall Google Cloud CLI via YUM/DNF on RedHat-based systems
  ansible.builtin.yum:
    name: google-cloud-cli
    state: absent
    autoremove: true
  when: ansible_os_family == "RedHat"
  become: true
