---

local:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    var1: value1
    ansible_python_interpreter: /usr/bin/python3

# webservers:
#   hosts:
#     web1:
#       ansible_host: 192.168.1.1
#     web2:
#       ansible_host: 192.168.1.2

# dbservers:
#   hosts:
#     db1:
#       ansible_host: 192.168.1.3

