#SPDX-License-Identifier: MIT-0
---
# tasks file for aws_install

- name: Install AWS CLI
  ansible.builtin.command:
    # cmd: aws --version
    cmd: pwd
  register: aws_version
  changed_when: false

- name: Print AWS CLI version
  ansible.builtin.debug:
    var: aws_version.stdout
